version: 2.1

orbs:
  node: circleci/node@5.1.0

executors:
  default:
    docker:
      - image: cimg/node:16.17.1
    environment:
      PARAM_CACHE_PATH: node_modules

anchors:
  filters-all: &filters-all
    branches:
      only: /.*/
    tags:
      only: /release/.*/
  filters-release: &filters-release
    branches:
      ignore: /.*/
    tags:
      only: /release\/.*/

jobs:
  node-run:
    executor: default
    parameters:
      npm-run:
        type: string
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
      - run: npm run << parameters.npm-run >>

workflows:
  ci-cd:
    jobs:
      - node-run:
          name: lint
          npm-run: lint
          filters: *filters-all
      - node-run:
          name: build
          npm-run: build
          filters: *filters-all
      - node-run:
          name: test
          npm-run: test
          filters: *filters-all
