version: 2.1

orbs:
  node: circleci/node@5.1.0

executors:
  default:
    docker:
      - image: cimg/node:16.17.1
    environment:
      PARAM_CACHE_PATH: node_modules

jobs:
  node-run:
    executor: default
    parameters:
      npm-run:
        type: string
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run << parameters.npm-run >>

workflows:
  ci-cd:
    jobs:
      - node-run:
          name: lint
          npm-run: lint
      - node-run:
          name: build
          npm-run: build
      - node-run:
          name: test
          npm-run: test
      - node-run:
          name: publish
          npm-run: semantic-release
          filters:
            branches:
              only: main
