version: 2.1

orbs:
  node: circleci/node@5.1.0
  coveralls: coveralls/coveralls@2.0.0

executors:
  default:
    docker:
      - image: cimg/node:16.17.1
    environment:
      PARAM_CACHE_PATH: node_modules
  node18:
    docker:
      - image: cimg/node:18.14.0
    environment:
      PARAM_CACHE_PATH: node_modules

jobs:
  node-run:
    executor: default
    parameters:
      npm-run:
        type: string
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          include-branch-in-cache-key: false
          override-ci-command: npm install
      - run: npm run << parameters.npm-run >>
  test:
    executor: default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          include-branch-in-cache-key: false
          override-ci-command: npm install
      - run: npm run test:cov
      - coveralls/upload

  release:
    executor: node18
    steps:
      - checkout
      - run: npx semantic-release --ci

workflows:
  ci-cd:
    jobs:
      - node-run:
          name: lint
          npm-run: lint
      - node-run:
          name: build
          npm-run: build
      - test:
          name: test
      - release:
          name: release
          requires:
            - lint
            - build
            - test
          filters:
            branches:
              only: main
