version: 2.1

orbs:
  node: circleci/node@5.1.0

executors:
  default:
    docker:
      - image: cimg/node:16.17.1
    environment:
      PARAM_CACHE_PATH: node_modules

anchors:
  filters-all: &filters-all
    branches:
      only: /.*/
    tags:
      only: /release/.*/
  filters-release: &filters-release
    branches:
      ignore: /.*/
    tags:
      only: /release\/.*/

parameters:
  cache-version:
    type: string
    default: v2

#jobs:
#  lint:
#    executor: default

workflows:
  ci-cd:
    jobs:
      - node/run:
          name: lint
          npm-run: lint
          cache-version: << pipeline.parameters.cache-version >>
          filters: *filters-all
      - node/run:
          name: build
          npm-run: build
          cache-version: << pipeline.parameters.cache-version >>
          filters: *filters-all
      - node/test:
          name: test
          test-results-path: junit.xml
          cache-version: << pipeline.parameters.cache-version >>
          filters: *filters-all
